site_name: uncle-archie
site_url: https://pages.charlesreid1.com/uncle-archie
repo_name: uncle-archie
repo_url: https://github.com/charlesreid1/uncle-archie
edit_uri: ""

copyright: 'Copyright &copy; 2018 <a href="https://charlesreid1.com">Charles Reid</a>, released under the <a href="https://opensource.org/licenses/MIT">MIT license</a> <br /><br />
<div>Icon made by Freepik, obtained from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>, used under a <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div> license.'

docs_dir: docs
site_dir: site
extra_css:
  - css/custom.css
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'teal'
    accent:  'teal'
  logo: 'images/unclearchiewt.svg'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

nav:
  - Index: 'index.md'
  - How It Works: 'how.md'
  - Quick Start: 'quick.md'
  - DevOps:
    - Flask: 'flask.md'
    - Nginx: 'nginx.md'
    - Startup Service: 'service.md'
  - Payloads and Hooks:
    - Payload Processing: 'payloads.md'
    - Hook Functions: 'hooks.md'
    - Activating Hooks in Github: 'github.md'
  - Acknowledgements: 'ack.md'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
