site_name: uncle-jenkins
site_url: https://pages.charlesreid1.com/uncle-jenkins
repo_name: uncle-jenkins
repo_url: https://github.com/charlesreid1/uncle-jenkins
edit_uri: ""

copyright: 'Copyright &copy; 2018 <a href="https://charlesreid1.com">Charles Reid</a>, released under the <a href="https://opensource.org/licenses/MIT">MIT license</a> <br /><br />
<div>Icon made by Freepik, obtained from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>, used under a <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div> license.'

docs_dir: docs
site_dir: site
extra_css:
  - css/custom.css
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'teal'
    accent:  'teal'
  logo: 'images/unclejenkinswt.svg'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
pages:
  - Index: 'index.md'

  - Preparing Jenkins:
    - Installing Jenkins: 'installing.md'
    - Nginx and Jenkins: 'nginx.md'
    - Configuring Jenkins: 'configuring.md'

  - Jenkins Plugins: 
    - Installing Plugins: 'plugins.md'
    - Github Pull Request Builder: 'plugins_ghprb.md'

  - Jobs:
    - Pull Request Builder: 'jobs_ghprb.md'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
